"""Chapter 11 v2 expected results: formula toolkit (11.2, 11.3), deeper lookups, GETPIVOTDATA, advanced dynamic
arrays, deeper Power Query, and the competition case 'Riverstone Rewards' (11.14).
Run from the book root:  python3 checks/ch11_expected_v2.py"""
import pandas as pd, numpy as np, math
S = pd.read_excel("companion/ch11/ch11_practice.xlsx", sheet_name="Sales", dtype={"customer_code": str})
S["sales_rep"] = S["sales_rep"].fillna("")
ok = S[S.status != "Cancelled"].copy()
def show(k, v): print(f"{k}: {v}")
tot = ok.net_revenue.sum()
print("== 11.2 conditional aggregation")
show("SUMIF Wholesale (all statuses)", S[S.segment=="Wholesale"].net_revenue.sum())
show("SUMIF Retail all vs valid", (S[S.segment=="Retail"].net_revenue.sum(), ok[ok.segment=="Retail"].net_revenue.sum()))
show("OR Retail+Hospitality valid", ok[ok.segment.isin(["Retail","Hospitality"])].net_revenue.sum())
q3 = ok[(ok.order_date>="2025-07-01")&(ok.order_date<="2025-09-30")].net_revenue.sum(); show("Q3 between dates", q3)
box = ok[ok.product_name.str.contains("Box")]; show("*Box* valid revenue, lines", (box.net_revenue.sum(), len(box)))
show("disc>=10 valid lines, revenue", (int((ok.discount_pct>=10).sum()), ok[ok.discount_pct>=10].net_revenue.sum()))
show("COUNTIFS lines Wholesale & Industrial & disc>0", int(((ok.segment=="Wholesale")&(ok.category=="Industrial")&(ok.discount_pct>0)).sum()))
show("AVERAGEIFS Wholesale line", round(ok[ok.segment=="Wholesale"].net_revenue.mean(),2))
show("AVERAGEIF Hospitality line", round(ok[ok.segment=="Hospitality"].net_revenue.mean(),2))
show("avg order value valid", round(tot/ok.order_id.nunique(),2))
show("avg order value by segment", (ok.groupby("segment").net_revenue.sum()/ok.groupby("segment").order_id.nunique()).round(2).to_dict())
show("MAXIFS Hospitality line", ok[ok.segment=="Hospitality"].net_revenue.max())
show("MINIFS first order date Harbour (0011)", str(ok[ok.customer_code=="0011"].order_date.min().date()))
show("MAXIFS last order Harbour", str(ok[ok.customer_code=="0011"].order_date.max().date()))
gross = (ok.quantity*ok.unit_price).sum(); show("gross before discount", gross)
show("weighted avg discount %", round((1 - tot/gross)*100, 2)); show("simple avg discount %", round(ok.discount_pct.mean(), 2))
show("SUMPRODUCT month 11 via MONTH()", ok[ok.order_date.dt.month==11].net_revenue.sum())
show("distinct customers by segment", ok.groupby("segment").customer_code.nunique().to_dict())
cr = ok.groupby("customer_name").net_revenue.sum().sort_values(ascending=False)
show("rank Metro Mart", int(cr.rank(ascending=False, method="min")["Metro Mart"]))
show("customer revenue ranks 1-8", cr.head(8).round(2).to_dict())
show("share of segment: Harbour in Wholesale %", round(cr["Harbour Traders"]/ok[ok.segment=="Wholesale"].net_revenue.sum()*100,1))
show("3rd largest line AGGREGATE", sorted(ok.net_revenue, reverse=True)[:3])
show("median Retail line", ok[ok.segment=="Retail"].net_revenue.median())
show("median valid line", ok.net_revenue.median())
dup = S.duplicated(["order_id","product_id"], keep=False).sum(); show("duplicate order_id+product_id lines in clean data", int(dup))
asof = pd.Timestamp("2025-12-31")
last = ok.groupby("customer_name").order_date.max(); days = (asof-last).dt.days
bk = pd.cut(days, [-1,30,60,90,10000], labels=["0-30","31-60","61-90","90+"]); show("recency buckets", bk.value_counts().sort_index().to_dict())
show("recency 90+ customers", sorted(days[days>90].index.tolist())); show("days since last: Sharma", int(days["Sharma Hardware"]))
fy = ok[ok.order_date>="2025-04-01"].net_revenue.sum(); show("FY2025-26 Apr-Dec", fy)
print("== 11.3 logic/text/dates")
show("SWITCH-like count", None)
show("DATEDIF months first-last Sharma", None)
sh = ok[ok.customer_code=="0001"]; f,l = sh.order_date.min(), sh.order_date.max()
show("Sharma first,last, whole months", (str(f.date()), str(l.date()), (l.year-f.year)*12 + l.month-f.month - (1 if l.day < f.day else 0)))
show("EDATE order 10001 +1", "2025-02-02"); show("EOMONTH(2025-01-02,1)", "2025-02-28")
show("WORKDAY 2025-12-24 +5", str(np.busday_offset("2025-12-24", 5, roll="forward")))
show("ISOWEEKNUM 2025-01-02", pd.Timestamp("2025-01-02").isocalendar()[1]); show("ISOWEEKNUM 2025-12-29", pd.Timestamp("2025-12-29").isocalendar()[1])
show("orders on weekends (Sat/Sun)", int(ok.drop_duplicates("order_id").order_date.dt.dayofweek.isin([5,6]).sum()))
show("order size bands (order level)", pd.cut(ok.groupby("order_id").net_revenue.sum(), [0,10000,25000,50000,1e9], right=False, labels=["<10k","10-25k","25-50k","50k+"]).value_counts().sort_index().to_dict())
print("== 11.4 lookups")
show("multi-criteria 10107 & 105", ok[(ok.order_id==10107)&(ok.product_id==105)].net_revenue.tolist())
show("XMATCH position of Metro Mart in sorted unique names", sorted(S.customer_name.unique()).index("Metro Mart")+1)
grid = ok.pivot_table(index="month_start", columns="segment", values="net_revenue", aggfunc="sum")
show("sum of a whole looked-up column Retail", grid["Retail"].sum())
show("Q4 Retail via rows 10-12", grid["Retail"].iloc[9:12].sum())
mon = ok.groupby(ok.order_date.dt.month).net_revenue.sum()
show("rolling last 3 months (Oct-Dec)", mon.loc[10:12].sum())
print("== GETPIVOTDATA")
show("Wholesale Q4", ok[(ok.segment=="Wholesale")&(ok.quarter=="Q4")].net_revenue.sum())
show("Retail total", ok[ok.segment=="Retail"].net_revenue.sum())
show("Farah Q3", ok[(ok.sales_rep=="Farah Khan")&(ok.quarter=="Q3")].net_revenue.sum())
show("running total by quarter", ok.groupby("quarter").net_revenue.sum().cumsum().to_dict())
show("rank of segment in Q1", ok[ok.quarter=="Q1"].groupby("segment").net_revenue.sum().rank(ascending=False).to_dict())
show("% of parent: Storage Box 25L within Storage", round(ok[ok.product_name=="Storage Box 25L"].net_revenue.sum()/ok[ok.category=="Storage"].net_revenue.sum()*100,1))
show("calculated field avg price per unit", round(tot/ok.quantity.sum(),2)); show("units", int(ok.quantity.sum()))
print("== dynamic arrays advanced")
show("TAKE top3 customers", cr.head(3).round(2).to_dict())
show("BYROW order totals >= 50000 count", int((ok.groupby("order_id").net_revenue.sum()>=50000).sum()))
show("largest order", ok.groupby("order_id").net_revenue.sum().sort_values(ascending=False).head(3).to_dict())
show("REDUCE/SCAN running max month", None)
print("== Power Query deeper")
g = ok.groupby(["month_start","segment"]).agg(rev=("net_revenue","sum"), lines=("order_id","size"), orders=("order_id","nunique")).reset_index()
show("Group By rows", len(g)); print(g[g.month_start=="2025-10-01"])
os_ = ok.groupby("order_id").net_revenue.sum()
show("conditional column bands order-level counts", pd.cut(os_, [0,10000,25000,1e9], right=False, labels=["Small","Medium","Large"]).value_counts().to_dict())
show("orders per customer max", ok.groupby("customer_name").order_id.nunique().sort_values(ascending=False).head(3).to_dict())
show("pivot column rows x cols", grid.shape)
