name: 'riverstone_dbt'
version: '1.0.0'
profile: 'riverstone_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  riverstone_dbt:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

snapshots:
  riverstone_dbt:
    +schema: snapshots
