-- Riverstone Supplies (fictional) — full sales dataset 2023–2025 (MySQL 8.0+).
-- Generated by generate_riverstone_full.py (seed 20230101). Every name and number is invented.
-- Run from the folder that holds the CSV files, with local loading allowed on both client and server:
--   mysql --local-infile=1 -u root -p < riverstone_full_setup_mysql.sql
--   (server: SET GLOBAL local_infile = 1;)
DROP DATABASE IF EXISTS riverstone_full;
CREATE DATABASE riverstone_full;
USE riverstone_full;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE customers (customer_id INTEGER PRIMARY KEY, customer_name VARCHAR(100) NOT NULL, city VARCHAR(50), segment VARCHAR(30) NOT NULL, signup_date DATE NOT NULL);
CREATE TABLE products (product_id INTEGER PRIMARY KEY, product_name VARCHAR(100) NOT NULL, category VARCHAR(30) NOT NULL, unit_price NUMERIC(10,2) NOT NULL, unit_cost NUMERIC(10,2) NOT NULL);
CREATE TABLE employees (employee_id INTEGER PRIMARY KEY, employee_name VARCHAR(100) NOT NULL, job_title VARCHAR(50) NOT NULL, manager_id INTEGER REFERENCES employees(employee_id));
CREATE TABLE orders (order_id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(customer_id), order_date DATE NOT NULL, status VARCHAR(20) NOT NULL, sales_rep_id INTEGER REFERENCES employees(employee_id));
CREATE TABLE order_items (order_item_id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(order_id), product_id INTEGER NOT NULL REFERENCES products(product_id), quantity INTEGER NOT NULL, unit_price NUMERIC(10,2) NOT NULL, discount_pct NUMERIC(5,2) NOT NULL DEFAULT 0);
CREATE TABLE sales_targets (target_month DATE PRIMARY KEY, target_revenue NUMERIC(12,2) NOT NULL);
CREATE TABLE leads (lead_id INTEGER PRIMARY KEY, created_at TIMESTAMP NOT NULL, company_name VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, source VARCHAR(30) NOT NULL, owner_id INTEGER REFERENCES employees(employee_id));
CREATE TABLE lead_stage_history (lead_id INTEGER NOT NULL REFERENCES leads(lead_id), stage VARCHAR(20) NOT NULL, entered_at TIMESTAMP NOT NULL, PRIMARY KEY (lead_id, stage));

LOAD DATA LOCAL INFILE 'employees.csv' INTO TABLE employees CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@employee_id, @employee_name, @job_title, @manager_id) SET employee_id = NULLIF(@employee_id, ''), employee_name = NULLIF(@employee_name, ''), job_title = NULLIF(@job_title, ''), manager_id = NULLIF(@manager_id, '');
LOAD DATA LOCAL INFILE 'customers.csv' INTO TABLE customers CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@customer_id, @customer_name, @city, @segment, @signup_date) SET customer_id = NULLIF(@customer_id, ''), customer_name = NULLIF(@customer_name, ''), city = NULLIF(@city, ''), segment = NULLIF(@segment, ''), signup_date = NULLIF(@signup_date, '');
LOAD DATA LOCAL INFILE 'products.csv' INTO TABLE products CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@product_id, @product_name, @category, @unit_price, @unit_cost) SET product_id = NULLIF(@product_id, ''), product_name = NULLIF(@product_name, ''), category = NULLIF(@category, ''), unit_price = NULLIF(@unit_price, ''), unit_cost = NULLIF(@unit_cost, '');
LOAD DATA LOCAL INFILE 'orders.csv' INTO TABLE orders CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@order_id, @customer_id, @order_date, @status, @sales_rep_id) SET order_id = NULLIF(@order_id, ''), customer_id = NULLIF(@customer_id, ''), order_date = NULLIF(@order_date, ''), status = NULLIF(@status, ''), sales_rep_id = NULLIF(@sales_rep_id, '');
LOAD DATA LOCAL INFILE 'order_items.csv' INTO TABLE order_items CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@order_item_id, @order_id, @product_id, @quantity, @unit_price, @discount_pct) SET order_item_id = NULLIF(@order_item_id, ''), order_id = NULLIF(@order_id, ''), product_id = NULLIF(@product_id, ''), quantity = NULLIF(@quantity, ''), unit_price = NULLIF(@unit_price, ''), discount_pct = NULLIF(@discount_pct, '');
LOAD DATA LOCAL INFILE 'sales_targets.csv' INTO TABLE sales_targets CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@target_month, @target_revenue) SET target_month = NULLIF(@target_month, ''), target_revenue = NULLIF(@target_revenue, '');
LOAD DATA LOCAL INFILE 'leads.csv' INTO TABLE leads CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@lead_id, @created_at, @company_name, @email, @source, @owner_id) SET lead_id = NULLIF(@lead_id, ''), created_at = NULLIF(@created_at, ''), company_name = NULLIF(@company_name, ''), email = NULLIF(@email, ''), source = NULLIF(@source, ''), owner_id = NULLIF(@owner_id, '');
LOAD DATA LOCAL INFILE 'lead_stage_history.csv' INTO TABLE lead_stage_history CHARACTER SET utf8mb4 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' LINES TERMINATED BY '\n' IGNORE 1 LINES (@lead_id, @stage, @entered_at) SET lead_id = NULLIF(@lead_id, ''), stage = NULLIF(@stage, ''), entered_at = NULLIF(@entered_at, '');
SET FOREIGN_KEY_CHECKS = 1;
CREATE VIEW sales_lines AS
SELECT o.order_id, o.order_date, o.customer_id, o.sales_rep_id, o.status,
       oi.product_id, p.category, oi.quantity,
       oi.quantity * oi.unit_price * (1 - oi.discount_pct / 100) AS net_revenue,
       oi.quantity * p.unit_cost AS product_cost
FROM orders AS o
JOIN order_items AS oi ON o.order_id = oi.order_id
JOIN products AS p ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled';

