-- Riverstone Supplies (fictional) — full sales dataset 2023–2025 (PostgreSQL 16+).
-- Generated by generate_riverstone_full.py (seed 20230101). Every name and number is invented.
-- Run from the folder that holds the CSV files:
--   createdb riverstone_full   (or: CREATE DATABASE riverstone_full;)
--   psql -d riverstone_full -f riverstone_full_setup_postgresql.sql
DROP VIEW IF EXISTS sales_lines;
DROP TABLE IF EXISTS lead_stage_history, leads, sales_targets, order_items, orders, products, customers, employees;
CREATE TABLE customers (customer_id INTEGER PRIMARY KEY, customer_name VARCHAR(100) NOT NULL, city VARCHAR(50), segment VARCHAR(30) NOT NULL, signup_date DATE NOT NULL);
CREATE TABLE products (product_id INTEGER PRIMARY KEY, product_name VARCHAR(100) NOT NULL, category VARCHAR(30) NOT NULL, unit_price NUMERIC(10,2) NOT NULL, unit_cost NUMERIC(10,2) NOT NULL);
CREATE TABLE employees (employee_id INTEGER PRIMARY KEY, employee_name VARCHAR(100) NOT NULL, job_title VARCHAR(50) NOT NULL, manager_id INTEGER REFERENCES employees(employee_id));
CREATE TABLE orders (order_id INTEGER PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customers(customer_id), order_date DATE NOT NULL, status VARCHAR(20) NOT NULL, sales_rep_id INTEGER REFERENCES employees(employee_id));
CREATE TABLE order_items (order_item_id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(order_id), product_id INTEGER NOT NULL REFERENCES products(product_id), quantity INTEGER NOT NULL, unit_price NUMERIC(10,2) NOT NULL, discount_pct NUMERIC(5,2) NOT NULL DEFAULT 0);
CREATE TABLE sales_targets (target_month DATE PRIMARY KEY, target_revenue NUMERIC(12,2) NOT NULL);
CREATE TABLE leads (lead_id INTEGER PRIMARY KEY, created_at TIMESTAMP NOT NULL, company_name VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL, source VARCHAR(30) NOT NULL, owner_id INTEGER REFERENCES employees(employee_id));
CREATE TABLE lead_stage_history (lead_id INTEGER NOT NULL REFERENCES leads(lead_id), stage VARCHAR(20) NOT NULL, entered_at TIMESTAMP NOT NULL, PRIMARY KEY (lead_id, stage));

\copy employees (employee_id, employee_name, job_title, manager_id) FROM 'employees.csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy customers (customer_id, customer_name, city, segment, signup_date) FROM 'customers.csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy products (product_id, product_name, category, unit_price, unit_cost) FROM 'products.csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy orders (order_id, customer_id, order_date, status, sales_rep_id) FROM 'orders.csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy order_items (order_item_id, order_id, product_id, quantity, unit_price, discount_pct) FROM 'order_items.csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy sales_targets (target_month, target_revenue) FROM 'sales_targets.csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy leads (lead_id, created_at, company_name, email, source, owner_id) FROM 'leads.csv' WITH (FORMAT csv, HEADER true, NULL '')
\copy lead_stage_history (lead_id, stage, entered_at) FROM 'lead_stage_history.csv' WITH (FORMAT csv, HEADER true, NULL '')
CREATE VIEW sales_lines AS
SELECT o.order_id, o.order_date, o.customer_id, o.sales_rep_id, o.status,
       oi.product_id, p.category, oi.quantity,
       oi.quantity * oi.unit_price * (1 - oi.discount_pct / 100) AS net_revenue,
       oi.quantity * p.unit_cost AS product_cost
FROM orders AS o
JOIN order_items AS oi ON o.order_id = oi.order_id
JOIN products AS p ON oi.product_id = p.product_id
WHERE o.status <> 'Cancelled';

ANALYZE;
