#!/usr/bin/env python3
"""make_calendar_tables.py - write the two calendar tables for the one-year database (Chapter 13, Pattern 5).

Creates calendar_tables_postgresql.sql and calendar_tables_mysql.sql next to this script.
Each file makes, in the riverstone_2025 database:
  calendar_months(month DATE PRIMARY KEY)  - 12 rows, the first day of each month of 2025
  calendar_days(day DATE PRIMARY KEY)      - 365 rows, every day of 2025
Run once:  python3 make_calendar_tables.py
Load:      psql -d riverstone_2025 -f calendar_tables_postgresql.sql
           mysql -uroot riverstone_2025 < calendar_tables_mysql.sql
"""
from datetime import date, timedelta
from pathlib import Path

HERE = Path(__file__).resolve().parent
months = [date(2025, m, 1) for m in range(1, 13)]
days = [date(2025, 1, 1) + timedelta(d) for d in range(365)]

def values(ds, per_line=6):
    items = [f"('{d.isoformat()}')" for d in ds]
    lines = [", ".join(items[i:i + per_line]) for i in range(0, len(items), per_line)]
    return ",\n".join(lines)

def body(header):
    return f"""{header}
-- Analyst to Architect, Chapter 13, Pattern 5: calendar tables for the one-year database (2025).
-- Generated by make_calendar_tables.py; do not edit by hand.
DROP TABLE IF EXISTS calendar_months;
CREATE TABLE calendar_months (
    month DATE PRIMARY KEY          -- the first day of each month
);
INSERT INTO calendar_months (month) VALUES
{values(months)};

DROP TABLE IF EXISTS calendar_days;
CREATE TABLE calendar_days (
    day DATE PRIMARY KEY            -- every day of the year
);
INSERT INTO calendar_days (day) VALUES
{values(days)};
"""

(HERE / "calendar_tables_postgresql.sql").write_text(body("-- PostgreSQL: run in the riverstone_2025 database."))
(HERE / "calendar_tables_mysql.sql").write_text(body("-- MySQL 8: creates the tables in riverstone_2025.\nUSE riverstone_2025;"))
print(f"wrote {len(months)} months and {len(days)} days")
