"""Rebuild TRACKER.md from tracker/register.csv.

Run from the repo root:  python tracker/make_tracker.py
Run it after every change to register.csv and commit both files together.
"""
import csv, re, collections, datetime, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATUSES = ["Open", "Approved", "Modify", "Rejected", "Deferred", "Fixed", "Verified"]
PART_ORDER = ["0–I", "0", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "Closing"]

def chkey(c):
    m = re.match(r"(\d+)([AB]?)", c or "")
    return (int(m.group(1)), m.group(2)) if m else (0, "")

rows = list(csv.DictReader(open(ROOT / "tracker/register.csv", encoding="utf-8")))
bad = [r["finding_id"] for r in rows if r["status"] not in STATUSES]
if bad:
    raise SystemExit(f"Unknown status on {len(bad)} rows, e.g. {bad[:5]}. Allowed: {STATUSES}")

def done(rs):  # closed = fixed, verified, rejected
    return sum(r["status"] in ("Fixed", "Verified", "Rejected") for r in rs)

tot = collections.Counter(r["status"] for r in rows)
out = []
out.append("# Tracker — Analyst to Architect fixes")
out.append("")
out.append(f"_Generated by `tracker/make_tracker.py` on {datetime.date.today():%d %b %Y} from `tracker/register.csv`. Do not edit by hand._")
out.append("")
closed = done(rows)
out.append(f"**Overall: {closed:,} of {len(rows):,} findings closed ({closed/len(rows):.0%}).** "
           + " · ".join(f"{s} {tot[s]:,}" for s in STATUSES if tot[s]))
out.append("")
out.append("Status meanings: Open = not yet decided · Approved = ready to fix · Modify = fix differently (see notes) · "
           "Rejected = no change · Deferred = later edition · Fixed = changed in source, PR open or merged · "
           "Verified = rebuilt PDF checked page by page.")
out.append("")
out.append("## By part")
out.append("")
out.append("| Part | Findings | High open | Open | Approved | Fixed | Verified | Rejected/Deferred | Closed |")
out.append("|---|---|---|---|---|---|---|---|---|")
byp = collections.defaultdict(list)
for r in rows: byp[r["part"]].append(r)
for p in PART_ORDER:
    rs = byp.get(p)
    if not rs: continue
    c = collections.Counter(r["status"] for r in rs)
    hi = sum(r["severity"] == "High" and r["status"] in ("Open", "Approved", "Modify") for r in rs)
    out.append(f"| {p} | {len(rs)} | {hi} | {c['Open']} | {c['Approved']+c['Modify']} | {c['Fixed']} | {c['Verified']} | "
               f"{c['Rejected']+c['Deferred']} | {done(rs)/len(rs):.0%} |")
out.append("")
out.append("## By chapter")
out.append("")
out.append("| Part | Ch | Content | Visual | High | Open | Approved | Fixed | Verified | Closed | Status |")
out.append("|---|---|---|---|---|---|---|---|---|---|---|")
bych = collections.defaultdict(list)
for r in rows: bych[(r["part"], r["chapter"])].append(r)
for (p, ch) in sorted(bych, key=lambda k: (PART_ORDER.index(k[0]) if k[0] in PART_ORDER else 99, chkey(k[1]))):
    rs = bych[(p, ch)]
    c = collections.Counter(r["status"] for r in rs)
    frac = done(rs) / len(rs)
    state = "✅ done" if c["Verified"] + c["Rejected"] + c["Deferred"] == len(rs) else \
            ("🔧 fixing" if c["Fixed"] or c["Verified"] else ("🟢 ready" if c["Approved"] + c["Modify"] else "⏳ awaiting decisions"))
    out.append(f"| {p} | {ch} | {sum(r['kind']=='content' for r in rs)} | {sum(r['kind']=='visual' for r in rs)} | "
               f"{sum(r['severity']=='High' for r in rs)} | {c['Open']} | {c['Approved']+c['Modify']} | {c['Fixed']} | "
               f"{c['Verified']} | {frac:.0%} | {state} |")
(ROOT / "TRACKER.md").write_text("\n".join(out) + "\n", encoding="utf-8")
print(f"TRACKER.md written: {closed}/{len(rows)} closed")
